### ISSUE TITLE
建议 SendxxxMessage 方法允许传递 context.Context 对象

### ISSUE THREAD

**Issue by hsldymq** [blinkbean/dingtalk#5]
问题描述:
在 DingTalk.sendMessage 中, ctx被硬编码为2秒超时. 

但有时候请求已经发送到钉钉,只是响应没有在2秒内到达, 这就导致返回了不正确的超时错误. 反映到现象就是尽管消息成功发到钉钉了,但是程序却返回了context deadline exceeded错误.

这会让调用方产生误判.假如调用方再重试,就会产生两条消息.当然不仅限于此.

建议:
将context对象开放调用方决定, 调用方自行根据自身的网络情况或其他方面的考虑来创建context

**Comment by Wanghongw** [comment]
希望官方也早点支持下

**Comment by blinkbean** [comment]
> 希望官方也早点支持下

已支持。
通过初始化时增加sendTimeout参数控制超时时间：
方式一：兼容之前版本，使用option方式控制。InitDingTalk(dingToken, ".", WithInitSendTimeout(time.Second*5))
方式二：使用SendxxxMessageWithCtx发送消息
